version: '3.8'

services:
  swing-trading-signal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: swing-trading-signal
    ports:
      - "8080:8080"
    environment:
      # Server Configuration
      - PORT=8080
      - ENV=production
      
      # Yahoo Finance API
      - YAHOO_FINANCE_BASE_URL=https://query1.finance.yahoo.com/v8/finance/chart
      
      # Gemini AI API
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_BASE_URL=https://generativelanguage.googleapis.com/v1beta/models
      - GEMINI_MODEL=gemini-pro
      
      # Trading Configuration
      - DEFAULT_MAX_HOLDING_PERIOD_DAYS=5
      - CONFIDENCE_THRESHOLD=70
      
      # Stock List Configuration (comma-separated)
      - STOCK_LIST=BBCA,BBRI,ANTM,ASII,ICBP,INDF,KLBF,PGAS,PTBA,SMGR,TLKM,UNTR,UNVR,WSKT
      
      # Telegram Bot Configuration
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - TELEGRAM_WEBHOOK_URL=${TELEGRAM_WEBHOOK_URL}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - trading-network

networks:
  trading-network:
    driver: bridge 